"""
Python export for PyDataFlow.

generate_python(nodes, edges) → str

Traverses the graph in topological order and calls each tool's to_code()
method to produce a standalone pandas script. The output requires only
pandas (and openpyxl for Excel nodes) — no PyDataFlow dependency at runtime.

Disabled nodes are emitted as comments. Nodes whose output ports are not
wired downstream are still emitted (the variable is assigned but unused).
"""

from __future__ import annotations

import re

from engine import Edge, Node, topological_sort
from nodes import get_tool

HEADER = """\
# Generated by PyDataFlow
import pandas as pd
"""


def _slugify(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", name.lower())
    s = re.sub(r"_+", "_", s).strip("_")
    return s or "node"


def _var(node: Node) -> str:
    tool = get_tool(node.kind)
    base = _slugify(tool.display_name if tool else node.kind)
    return f"df_{base}_{node.id}"


def generate_python(nodes: list[Node], edges: list[Edge]) -> str:
    try:
        ordered = topological_sort(nodes, edges)
    except ValueError as e:
        return f"# Export failed: {e}\n"

    nid_map: dict[str, Node] = {n.id: n for n in nodes}
    node_vars: dict[str, str] = {}
    lines: list[str] = [HEADER]

    for node in ordered:
        tool = get_tool(node.kind)
        if tool is None:
            lines.append(f"# Unknown tool: {node.kind}")
            continue
        if node.disabled:
            lines.append(f"# [{tool.display_name}] skipped (disabled)")
            continue

        out_var = _var(node)
        node_vars[node.id] = out_var

        # Gather input vars aligned to tool.ins
        input_vars: list[str] = []
        for port in tool.ins:
            src_var = "df_unknown"
            for e in edges:
                if e.dst_node == node.id and e.dst_port == port:
                    src_base = node_vars.get(e.src_node, "")
                    src_node = nid_map.get(e.src_node)
                    src_tool = get_tool(src_node.kind) if src_node else None
                    if src_tool and len(src_tool.outs) > 1:
                        src_var = f"{src_base}_{e.src_port}"
                    else:
                        src_var = src_base or "df_unknown"
                    break
            input_vars.append(src_var)

        # Which output ports are actually wired downstream?
        co = list(dict.fromkeys(e.src_port for e in edges if e.src_node == node.id))
        connected_outs = co if co else None  # None → emit all

        code_lines = tool.to_code(node.params, input_vars, out_var, connected_outs)
        if code_lines:
            lines.append(f"\n# --- {tool.display_name} ({node.id}) ---")
            lines.extend(code_lines)

    return "\n".join(lines) + "\n"
